eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: basic_servic
#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.discern.car.dao
  mapperLocations: classpath*:mapper/*.xml

#开发配置
spring:
#  profiles: dev

  datasource:
    url: jdbc:mysql://119.29.208.119:3306/car?useUnicode=true&rewriteBatchedStatements=true&useSSL=false&characterEncoding=utf8
#    url: jdbc:mysql://119.29.208.119:3306/car?useUnicode=true&characterEncoding=utf8mb4&rewriteBatchedStatements=true&useSSL=false
    username: xiaoxu
    password: xiaoxu
    driver-class-name: com.mysql.jdbc.Driver

